### PR TITLE
Fault tolerance improvements

### PR DESCRIPTION
**Pull request by technetos**
Dont kill the main thread when we get an error

### CODE REVIEW

**Comment by technetos** [comment]
@pietroalbini I am removing [this line] to prevent the main thread from being killed when an error propogates up.  Removing call to `exit(1)` doesnt have any impact on the deployment does it?

[this line]: https://github.com/rust-lang/discord-mods-bot/pull/73/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcL227

**Review by khionu — APPROVED** [review]

**Comment by pietroalbini** [comment]
It should not, but I'm wondering why you want to remove it.

**Comment by technetos** [comment]
> It should not, but I'm wondering why you want to remove it.

When AWS restarted the postgres instance the other day, the error made it all the way to the main fn.  The error was logged and it killed the main thread, leaving only the jobs thread running and requiring the bot to be restarted.  Removing the call to `exit(1)` allows the bot to continue running when an error propogates all the way to main.

**Comment by pietroalbini** [comment]
Hmm, how did that happen? My understanding is that `exit(1)` terminates the process, which can't leave the other threads running.

**Comment by technetos** [comment]
> Hmm, how did that happen? My understanding is that `exit(1)` terminates the process, which can't leave the other threads running.

Ah, you may be right, from the logs it seemed like the jobs thread was still running but it may have also died.  Regardless, Id like to prevent errors from propogating up and killing the running instance.

**Comment by pietroalbini** [comment]
I don't think removing the `std::process::exit(1)` call will achieve what you want: if that piece of code is reached the `app()` function already returned, and the application will exit since the end of `main()` was reached. The only thing the call to `exit` does is overriding the exit code to be `1` (properly signaling an error happened).

If you want an error in a command not to close the application you'll need to handle it, probably on the serenity side.

**Comment by technetos** [comment]
:thinking: Your totally correct.  Closing.

**Pull request closed without merging**
