### PR TITLE
adjusted responses of `?docs`

### PR DESCRIPTION
**Pull request by tinaun**
* made it more explicit it searches for crates, not items
* provided overrides for rustc crates not visible on crates.io (std, core, etc)

### CODE REVIEW

**Comment by technetos** [comment]
So I just glanced over this and it looks great!  Ill review it later today and get it merged in.  Thanks!

Does this also take care of https://github.com/rust-lang/discord-mods-bot/issues/37?

**Comment by technetos** [comment]
Ok, this is great and ill merge it in a moment.  It does not look like this fulfills #37 since `?docs std` simply links to the docs and doesnt search items.

**Comment by tinaun** [comment]
wait i misspelled rust-lang as rust_lang, oops

**Comment by tinaun** [comment]
also for #37 i think calling out to a search engine that already has doc.rust-lang indexed would be our best bet, unless old documentation is called up

**Pull request merged**
