### PR TITLE
Database transactions

### PR DESCRIPTION
**Pull request by technetos**

### CODE REVIEW

**Comment by khionu** [comment]
We're using `lazy_static` over `once_cell`?

**Comment by pietroalbini** [comment]
Sorry, but I don't have the time to review this right now.

**Comment by technetos** [comment]
@khionu Yeah we are, it works, why use `once_cell`?

**Comment by khionu** [comment]
The `once_cell` crate is just as heavy, but provides more functionalities. Additionally, since `once_cell::Lazy` isn't a macro, it works better with IDEs.

**Pull request merged**
